import random
import tkinter as tk
from time import sleep
from tkinter import ttk
from colorama import Fore
class App():
    def __init__(self):
        self.root = tk.Tk()
        self.root.geometry('350x200')
        self.root.title('FakeHackScreen 1.2.0')
        self.mainframe = tk.Frame(self.root,background='white')
        self.mainframe.pack(fill='both', expand=True)
        
        self.text = ttk.Label(self.mainframe, text='Choose a display:',background='white',font=('Arial', 15))
        self.text.grid(row=0,column=0)
        options = ["0's and 1's", 'Command Text (LAGS)']
        self.selection = ttk.Combobox(self.mainframe,state='readonly',values=options)
        self.selection.grid(row=2,column=0, sticky='NWES', pady=10)
        self.startbutton = ttk.Button(self.mainframe, text='Start', command=self.start)
        self.startbutton.grid(row=2,column=1,pady=10)
        self.stopbutton = ttk.Button(self.mainframe, text='Stop', command=self.stop)
        self.stopbutton.grid(row=2,column=2,pady=10)
        self.root.mainloop()
        return
    def randomipfail(self):
        if run:
            self.randomized = random.choice(self.successfail)
            if self.randomized == 'Admin> Success!':
                print('Admin> Success!')
                self.root.after(1,self.screen)
            else:
                self.root.after(1,self.randomipfail)
    def screen(self):
        if run:
            display = self.selection.get()
            if display == "0's and 1's":
                nums = ''.join(random.sample('10' * 1_000, random.randint(1,999)))
                print(f'{Fore.LIGHTGREEN_EX}{nums}')
                self.root.after(1,self.screen)
            elif display == 'Command Text (LAGS)':
                #Don't use this to steal IP addresses, this is auto generated by "ipvoid.com".
                randomip = f'{random.randint(1,254)}.{random.randint(1,254)}.{random.randint(1,254)}.{random.randint(1,254)}'
                self.successfail = ['Admin> Success!','Admin> Failed, trying again.']
                print(f'{Fore.LIGHTGREEN_EX}Admin> Hacking IP {randomip}')
                self.randomized = random.choice(self.successfail)
                print(f'{Fore.LIGHTGREEN_EX}{self.randomized}')
                if self.randomized == 'Admin> Failed, trying again.':
                    self.root.after(1,self.randomipfail)
                delay = random.randint(1,100)
                sleep(1/int(delay))
                self.root.after(1,self.screen)
            else:
                print('Action not detected!')
    def start(self):
        global run
        run = True
        self.startbutton["state"] = "disabled"
        self.stopbutton["state"] = "enable"
        print(f'{Fore.WHITE}Started!')
        self.root.after(1,self.screen)
    def stop(self):
        global run
        run = False
        self.stopbutton["state"] = "disabled"
        self.startbutton["state"] = "enable"
        print(f'{Fore.WHITE}Stopped!')
        self.root.after(1,self.screen)
if __name__ == '__main__':
    App()
